### ISSUE TITLE
fail to load My/Schema 

### ISSUE THREAD

**Issue by hkamuc** [sboehringer/mediathek#1]
I have installed mediathek following the instructions in the Readme - but when I try to do an updatedb I get the following error:

**pi@raspi1-dlna ~/src/mediathek $ ./mediathek-worker.pl --updatedb
Can't locate My/Schema.pm in @INC (@INC contains: /home/pi/.local/share/applications/mediathek/schema /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /usr/share/perl/5.14/Module/Load.pm line 27.
Can't locate My/Schema in @INC (@INC contains: /home/pi/.local/share/applications/mediathek/schema /etc/perl /usr/local/lib/perl/5.14.2 /usr/local/share/perl/5.14.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.14 /usr/share/perl/5.14 /usr/local/lib/site_perl .) at /usr/share/perl/5.14/Module/Load.pm line 27.**

Btw.: I tried to run it in Lubuntu 14.04 and in the recent Raspian

Someone can help me?

**Comment by sboehringer** [comment]
Have you run --createdb first?
Did this give you any error messages?

**Comment by hkamuc** [comment]
Hi Stefan

It is working now...

Many thanks for your quick reply!

Kind regards

Hans

On 23. März 2015 11:06:42 MEZ, "Stefan Böhringer" notifications@github.com wrote:

> Have you run --createdb first?
> Did this give you any error messages?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/sboehringer/mediathek/issues/1#issuecomment-84925963

## 

Sent from Kaiten Mail. Please excuse my brevity.
