### ISSUE TITLE
Log file available?

### ISSUE THREAD

**Issue by meinnamehier** [sboehringer/mediathek#4]
(Sorry: I only know this way in Github to ask you something)

Is there a log available? It would be great to see confirmation that the autofetches worked and what happened (how many instances found, how much data received, where it was saved etc.)

This could also be written into the database. Currently, the "tv_recoding" table only shows the ID.
For instance, I have a line in "tv_recording" that shows the ID 11551, but that is not an ID in "tv_item". I wish i knew what happended here...

Oh, and of course: Thanks for the great work! I really appreciate your effort!

**Comment by sboehringer** [comment]
If you run from the command line you see the output directly. If you use a cronjob, a local email is send with the command output which can be accessed using the `mail` command line client.
