### ISSUE TITLE
Running via cron: ./parse-videolist-json.pl: not found

### ISSUE THREAD

**Issue by meinnamehier** [sboehringer/mediathek#5]
Hi - it's me again, i hope i am not too bothersome.

After a fresh restart the cronjob regarding --updatedb does not work properly, i think it has to do with the paths. This is the output:

> Fetching http://zdfmediathk.sourceforge.net/update-json.xml --> /home/osmc/.local/share/applications/mediathek/servers.xml [No: 0/1]
> mediathek-worker.pl[880]: Fetching http://hosting1735.af906.netcup.net/filme/Filmliste-akt.xz --> /home/osmc/.local/share/applications/mediathek/database-json-0.xz [No: 8/16]
> mediathek-worker.pl[880]: Now: 2016-03-13 23:00:14, pruning older than: 2016-03-03 23:00:14
> mediathek-worker.pl[880]: About to delete 4377 items.
> sh: 1: ./parse-videolist-json.pl: not found
> mediathek-worker.pl[880]: Added 0 items.

This is my crontab entry. I left the PATH-part like in your documentation:

```
SHELL=/bin/bash
PERL5LIB=:/home/osmc/src/mediathek:/home/osmc/bin
PATH=/home/osmc/bin:/home/osmc/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/sbin:/usr/sbin:/usr/osmc/b$

00 23 * * * /home/osmc/src/mediathek/mediathek-worker.pl --updatedb &>> /home/osmc/src/mediathek/logs/`date +\%Y\%m\%d`$
```

Do I need to change the PATHs to include something more?

**Comment by sboehringer** [comment]
This would have to be:

```

00 23 * * *  cd /home/osmc/src/mediathek ; ./mediathek-worker.pl --updatedb >> /home/osmc/src/mediathek/logs/`date +\%Y\%m\%d`
```
