### ISSUE TITLE
Exclude two values in search

### ISSUE THREAD

**Issue by meinnamehier** [sboehringer/mediathek#6]
Hi, me again!
I am certainly dense, but i cannot figure this out:
I want to exclude two different values when doing a search, like this:
title:!%Hörfassung%
title:!%Audiodeskription%
How do i achieve this? I have tried different methods (title:!%Hörfassung% && !%Audiodeskription%) etc but it doesn't work.
When i use title: twice, only the second argument is evaluated.
My goal is to have a search a search for tatort, which excludes Hörfassung and Audiodeskription on the title. I started off with your example:
`./mediathek-worker.pl --search 'channel:ARD;topic:%Tatort%;title:!%Hörfassung%;duration:>45'` and am trying to add onto that.

**Comment by sboehringer** [comment]
This should work:
`'channel:ARD;topic:%Tatort%;title:!%Hörfassung%;title:!%Audiodeskription%;duration:>45'`
If it doesn't work it's a bug (haven't tested).

**Comment by meinnamehier** [comment]
No, it unfortunately doesn't work. The script then only takes the last title: query, in this case "!%Audiodeskription%"

**Comment by meinnamehier** [comment]
Hi, any update on this? My wife keeps nagging me to automatically download the Tatort, but I don't want to load 2 versions all the time. (Since apparently deleted shows get redownloaded, it is even worse)

**Comment by sboehringer** [comment]
It is indeed a bug. I quickly investigated. The documentation of the module used, namely DBIx is not 100% clear on how to provide the and-clause. I will have to experiment to find out.

**Comment by sboehringer** [comment]
A workaround for now would be to include channel in the search to avoid duplicates.

**Comment by meinnamehier** [comment]
Hm, I don't understand - the parameter channel:ARD is already set. All Tatorts are comfing from the ARD-Mediathek

**Comment by sboehringer** [comment]
fixed as of 24.10.2016 (cave: other regressions might be present at the moment).
