### ISSUE TITLE
Can not start, My::Schema is missing

### ISSUE THREAD

**Issue by tuxflo** [sboehringer/mediathek#7]
I tried to install the mediathek on a ubuntu 14.04 Docker conatiner using the Installation notes. When I try to do a search like `./mediathek-worker.pl --search 'title:%Tatort%'` the following error message occurs:

```
Can't locate My/Schema.pm in @INC (you may need to install the My::Schema module) (@INC contains: //.local/share/applications/mediathek/schema /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /usr/local/lib/site_perl .) at /usr/share/perl/5.18/Module/Load.pm line 27.
```

Thanks for helping,
Flo

**Comment by meinnamehier** [comment]
Take a look at this:
https://github.com/sboehringer/mediathek/issues/1
and at this:
https://github.com/sboehringer/mediathek/wiki/Getting-Started
