### ISSUE TITLE
AddSearch is not working

### ISSUE THREAD

**Issue by tkampmey** [sboehringer/mediathek#8]
Hello,
I just tried the method addsearch and I got the following error:
Can't call method "id" on an undefined value at mediathekLogic.pm line 290.
The method search works very good.
I just for my test the following query:
--search 'title:Tatort%;title:!%Audiodeskription%' -> that was working
--addsearch 'title:Tatort%;title:!%Audiodeskription%' -> this is not working.

Can you check this?
Many thanks,
 Thomas

**Comment by sboehringer** [comment]
Please report your OS, mediathek commit version, and the output of:
DBIC_TRACE=1 ./mediathek-worker.pl --addsearch  'title:Tatort%;title:!%Audiodeskription%'

The script is in transition at the moment to allow scraping of youtube as well. Version 1.1 would be the stable version at the moment.

**Comment by tkampmey** [comment]
Hello,
my OS is Ubuntu 16.04, the mediathek version is from 1.1.17 18:23, and the output is:

```
SELECT me.id, me.name, me.parameters FROM tv_type me WHERE ( name = ? ): 'mediathek'
Use of uninitialized value $type in concatenation (.) or string at mediathekLogic.pm line 289.
mediathek-worker.pl[4412]: Type: 
INSERT INTO tv_grep ( expression, type) VALUES ( ?, ? ): 'title:Tatort%;title:!%Audiodeskription%', '1'
SELECT me.id, me.expression, me.destination, me.witness, me.type, type.id, type.name, type.parameters FROM tv_grep me  JOIN tv_type type ON type.id = me.type: 
Can't locate object method "" via package "My::Schema::Result::TvGrep" at TempFileNames.pm line 1283.

```

**Comment by sboehringer** [comment]
Did you start from a fresh checkout or did you update with git pull? In the latter case, please start fresh:
```
 rm -rf ~/.local/share/applications/mediathek
./mediathekWorker.pl --createdb
./mediathekWorker.pl --updatedb
```

**Comment by sboehringer** [comment]
On a current checkout and a fresh database (see comment above), the problem cannot be reproduced.
